version: '3'
services:
  app:
    build: .  # Build from the Dockerfile in the current directory
    container_name: go_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${POSTGRES_URL}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RPC_URL: ${RPC_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
    ports:
      - "8080:8080"
    networks:
      - app-network

  redis:
    image: redis:7.2.4-alpine
    container_name: redis_service
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./opt/redis:/data
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./opt/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_service
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
